#!/usr/bin/python
# coding: utf-8
# Copyright (C) 2010 Lucas Alvares Gomes <lucasagomes@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

__all__ = ["LANGUAGES"]

LANGUAGES = {
  "af": _("Afrikaans"),
  "sq": _("Albanian"),
  "am": _("Amharic"),
  "ar": _("Arabic"),
  "hy": _("Armenian"),
  "az": _("Azerbaijani"),
  "eu": _("Basque"),
  "be": _("Belarusian"),
  "bn": _("Bengali"),
  "bh": _("Bihari"),
  "bg": _("Bulgarian"),
  "my": _("Burmese"),
  "ca": _("Catalan"),
  "chr":_("Cherokee"),
  "zh": _("Chinese"),
  "hr": _("Croatian"),
  "cs": _("Czech"),
  "da": _("Danish"),
  "dv": _("Dhivehi"),
  "nl": _("Dutch"),
  "en": _("English"),
  "eo": _("Esperanto"),
  "et": _("Estonian"),
  "tl": _("Filipino"),
  "fi": _("Finnish"),
  "fr": _("French"),
  "gl": _("Galician"),
  "ka": _("Georgian"),
  "de": _("German"),
  "el": _("Greek"),
  "gn": _("Guarani"),
  "gu": _("Gujarati"),
  "iw": _("Hebrew"),
  "hi": _("Hindi"),
  "hu": _("Hungarian"),
  "is": _("Icelandic"),
  "id": _("Indonesian"),
  "iu": _("Inuktitut"),
  "ga": _("Irish"),
  "it": _("Italian"),
  "ja": _("Japanese"),
  "kn": _("Kannada"),
  "kk": _("Kazakh"),
  "km": _("Khmer"),
  "ko": _("Korean"),
  "ku": _("Kurdish"),
  "ky": _("Kyrgyz"),
  "lo": _("Laothian"),
  "lv": _("Latvian"),
  "lt": _("Lithuanian"),
  "mk": _("Macedonian"),
  "ms": _("Malay"),
  "ml": _("Malayalam"),
  "mt": _("Maltese"),
  "mr": _("Marathi"),
  "mn": _("Mongolian"),
  "ne": _("Nepali"),
  "no": _("Norwegian"),
  "or": _("Oriya"),
  "ps": _("Pashto"),
  "fa": _("Persian"),
  "pl": _("Polish"),
  "pt": _("Portuguese"),
  "pa": _("Punjabi"),
  "ro": _("Romanian"),
  "ru": _("Russian"),
  "sa": _("Sanskrit"),
  "sr": _("Serbian"),
  "sd": _("Sindhi"),
  "si": _("Sinhalese"),
  "sk": _("Slovak"),
  "sl": _("Slovenian"),
  "es": _("Spanish"),
  "sw": _("Swahili"),
  "sv": _("Swedish"),
  "tg": _("Tajik"),
  "ta": _("Tamil"),
  "tl": _("Tagalog"),
  "te": _("Telugu"),
  "th": _("Thai"),
  "bo": _("Tibetan"),
  "tr": _("Turkish"),
  "uk": _("Ukrainian"),
  "ur": _("Urdu"),
  "uz": _("Uzbek"),
  "ug": _("Uighur"),
  "vi": _("Vietnamese"),
  "cy": _("Welsh"),
  "yi": _("Yiddish")
}
